CREATE TABLE "EMPLOYEE" (
  "NAME" VARCHAR2(32) PRIMARY KEY USING INDEX ENABLE,
  "ADDRESS" VARCHAR2(64)
);
  
CREATE TABLE "WORKER" ( 
  "EMPLOYEE.NAME" VARCHAR2(32) PRIMARY KEY USING INDEX ENABLE, 
  "PRODUCTION_LIMIT" INTEGER,
  FOREIGN KEY ("EMPLOYEE.NAME") REFERENCES EMPLOYEE("NAME"),
  CHECK ("PRODUCTION_LIMIT">0)
);

CREATE TABLE "QUALITYCONTROLLER" (
  "EMPLOYEE.NAME" VARCHAR2(32) PRIMARY KEY USING INDEX ENABLE,
  "PRODUCT_TYPE" INTEGER,
  FOREIGN KEY ("EMPLOYEE.NAME") REFERENCES EMPLOYEE("NAME"),
  CONSTRAINT "CHK_RODUCT_TYPE" CHECK ("PRODUCT_TYPE" IN (1, 2, 3))
);
  
CREATE TABLE "TECHNICALSTAFF" (
  "EMPLOYEE.NAME" VARCHAR2(32) PRIMARY KEY USING INDEX ENABLE,
  "EDUCATION" VARCHAR2(4) NOT NULL,
  "TECHNICAL_POSITION" VARCHAR2(16) NOT NULL,
  FOREIGN KEY ("EMPLOYEE.NAME") REFERENCES EMPLOYEE("NAME")
);

CREATE TABLE "CUSTOMER" (
  "NAME" VARCHAR2(32) PRIMARY KEY USING INDEX ENABLE,
  "ADDRESS" VARCHAR2(32)
);
 

CREATE TABLE "PRODUCT" (
  "PID" INTEGER PRIMARY KEY USING INDEX ENABLE,
  "PRODUCTION_DATE" DATE,
  "PRODUCTION_TIME_MINUTES" INTEGER,
  "SIZE" VARCHAR2(8),
  "W.NAME" VARCHAR2(32),
  "QC.NAME" VARCHAR2(32),
  "TS.NAME" VARCHAR2(32),
  "REPAIR_DATE" DATE,
  "CUSTOMER.NAME" VARCHAR2(32),
  CHECK ("PRODUCTION_TIME_MINUTES">0),
  FOREIGN KEY ("W.NAME") REFERENCES "WORKER"("EMPLOYEE.NAME"),
  FOREIGN KEY ("QC.NAME") REFERENCES "QUALITYCONTROLLER"("EMPLOYEE.NAME")
);

CREATE TABLE "ACCOUNT" (
  "NUMBER" INTEGER PRIMARY KEY USING INDEX ENABLE,
  "DATE_EST" DATE,
  "COST" INTEGER,
  "PRODUCT.PID" INTEGER,
  CHECK ("COST">0),
  FOREIGN KEY ("PRODUCT.PID") REFERENCES "PRODUCT"("PID")
);

CREATE TABLE "PRODUCT1" (
  "PID" INTEGER PRIMARY KEY USING INDEX ENABLE,
  "SOFTWARE" VARCHAR2(128),
  "ACCOUNT.NUMBER" INTEGER,
  FOREIGN KEY ("PID") REFERENCES "PRODUCT"("PID"),
  FOREIGN KEY ("ACCOUNT.NUMBER") REFERENCES "ACCOUNT"("NUMBER")
);

CREATE TABLE "PRODUCT2" (
  "PID" INTEGER PRIMARY KEY USING INDEX ENABLE,
  "COLOR" VARCHAR2(16),
  "ACCOUNT.NUMBER" INTEGER,
  FOREIGN KEY ("PID") REFERENCES "PRODUCT"("PID"),
  FOREIGN KEY ("ACCOUNT.NUMBER") REFERENCES "ACCOUNT"("NUMBER")
);

CREATE TABLE "PRODUCT3" (
  "PID" INTEGER PRIMARY KEY USING INDEX ENABLE,
  "WEIGHT" INTEGER,
  "ACCOUNT.NUMBER" INTEGER,
  FOREIGN KEY ("PID") REFERENCES "PRODUCT"("PID"),
  FOREIGN KEY ("ACCOUNT.NUMBER") REFERENCES "ACCOUNT"("NUMBER")
);



CREATE TABLE "ACCIDENT" (
  "NUMBER" INTEGER PRIMARY KEY USING INDEX ENABLE,
  "DATE" DATE,
  "DAYS_LOST" INTEGER,
  "PRODUCT.PID" INTEGER,
  "EMPLOYEE.NAME" VARCHAR2(32),
  FOREIGN KEY ("PRODUCT.PID") REFERENCES "PRODUCT"("PID"),
  FOREIGN KEY ("EMPLOYEE.NAME") REFERENCES "EMPLOYEE"("NAME")
);

CREATE TABLE "COMPLAINT" (
  "CID" INTEGER PRIMARY KEY USING INDEX ENABLE,
  "CDATE" DATE,
  "DESCRIPTION" VARCHAR2(512),
  "TREATMENT" VARCHAR2(16),
  "CUSTOMER.NAME" VARCHAR2(32),
  "PRODUCT.PID" INTEGER,
  FOREIGN KEY ("PRODUCT.PID") REFERENCES "PRODUCT"("PID"),
  FOREIGN KEY ("CUSTOMER.NAME") REFERENCES "CUSTOMER"("NAME")
);


CREATE OR REPLACE PROCEDURE INSERT_NEW_EMPLOYEE ("NAME" IN VARCHAR2, 
  "ADDRESS" IN VARCHAR2)
IS
BEGIN
  
  INSERT INTO EMPLOYEE VALUES("NAME", "ADDRESS");
  
END;
/



CREATE OR REPLACE PROCEDURE INSERT_NEW_PRODUCT ("PID" IN INTEGER, 
  "PRODUCTION_DATE" IN VARCHAR2, "PRODUCTION_TIME_MINUTES" IN INTEGER, 
  "SIZE" IN VARCHAR2, "W.NAME" IN VARCHAR2, "QC.NAME" IN VARCHAR2, 
  "TS.NAME" IN VARCHAR2, "REPAIR_DATE" IN DATE, "CUSTOMER.NAME" IN VARCHAR2)

IS
  
BEGIN
  
  INSERT INTO PRODUCT VALUES("PID", 
  "PRODUCTION_DATE", "PRODUCTION_TIME_MINUTES", 
  "SIZE", "W.NAME", "QC.NAME", "TS.NAME",
  "REPAIR_DATE" , "CUSTOMER.NAME");
  
END;
/


CREATE OR REPLACE PROCEDURE INSERT_NEW_CUSTOMER ("NAME" IN VARCHAR2, "ADDRESS" IN VARCHAR2)

IS
  
BEGIN
  
  INSERT INTO CUSTOMER VALUES("NAME", "ADDRESS");
  
END;
/



CREATE OR REPLACE PROCEDURE "CUSTOMER_PURCHASE" ("NAME" IN VARCHAR2, "PRODUCT_ID" IN INTEGER)

IS
  
BEGIN
  
  UPDATE PRODUCT
  SET "CUSTOMER.NAME"="NAME"
  WHERE "PID"="PRODUCT_ID";
  
END;
/



CREATE OR REPLACE PROCEDURE INSERT_NEW_ACCOUNT ("NUMBER" IN INTEGER, "DATE_EST" IN DATE, "COST" IN INTEGER, "PID" IN INTEGER)

IS
  
BEGIN
  
  INSERT INTO "ACCOUNT" VALUES("NUMBER", "DATE_EST", "COST", "PID");
  
END;
/




CREATE OR REPLACE PROCEDURE INSERT_NEW_COMPLAINT ("CID" IN INTEGER,
  "CDATE" IN DATE, "DESCRIPTION" IN VARCHAR2, "TREATEMENT" IN VARCHAR2,
  "CUSTOMER.NAME" IN VARCHAR2,"PRODUCT.PID" IN INTEGER)
IS
  
BEGIN
  
  INSERT INTO "COMPLAINT" VALUES("CID","CDATE", "DESCRIPTION", 
  "TREATEMENT","CUSTOMER.NAME","PRODUCT.PID");
  
END;
/


CREATE OR REPLACE PROCEDURE INSERT_NEW_ACCIDENT ("NUMBER" INTEGER,
  "DATE" DATE, "DAYS_LOST" INTEGER, "PRODUCT.PID" INTEGER,
  "EMPLOYEE.NAME" VARCHAR2)
IS
  
BEGIN
  
  INSERT INTO "ACCIDENT" VALUES("NUMBER",
  "DATE", "DAYS_LOST", "PRODUCT.PID",
  "EMPLOYEE.NAME");
  
END;
/



SELECT "PID" FROM PRODUCT WHERE "QC.NAME"='Parker';








